/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalaDeEncuentroRouteImport } from './routes/sala-de-encuentro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaDeEncuentroRoute = SalaDeEncuentroRouteImport.update({
  id: '/sala-de-encuentro',
  path: '/sala-de-encuentro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sala-de-encuentro': typeof SalaDeEncuentroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sala-de-encuentro': typeof SalaDeEncuentroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sala-de-encuentro': typeof SalaDeEncuentroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sala-de-encuentro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sala-de-encuentro'
  id: '__root__' | '/' | '/sala-de-encuentro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SalaDeEncuentroRoute: typeof SalaDeEncuentroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sala-de-encuentro': {
      id: '/sala-de-encuentro'
      path: '/sala-de-encuentro'
      fullPath: '/sala-de-encuentro'
      preLoaderRoute: typeof SalaDeEncuentroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SalaDeEncuentroRoute: SalaDeEncuentroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
